name: dotnet

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run ======================> check the logs here
      run: dotnet run --project ./CompileTimeMethodExecutionGenerator.Example/CompileTimeMethodExecutionGenerator.Example.csproj
